### ISSUE TITLE
Create a temporary CRON schedule in DIEM 

### ISSUE THREAD

**Issue by JHilge** [IBM/diem#34]
[Requirement for temporary CRON schedule .docx](https://github.com/IBM/diem/files/6144196/Requirement.for.temporary.CRON.schedule.docx)

**Comment by huineng** [comment]
so basically we have a pipeline with 2 jobs (or one job with some pre condition logic ) but let's say one job that does pre-work
and has logic to check the current data and adapt that if it's the first.
Then that job also needs to check values in the source database and if not met , reschedule to next day
(ps can it be that next day is also the first ? and hence +7 days ?)

And what if all checks are complete, does it then need to set the day for the next month? or a fix date ?

Of course this can be done in python 

```
check today 
if today == 1st :
  next schedule = today +7
  STOP
else:
  run query to check 
  if check not ok:
     next schedule is today +1
     STOP
 else 
  next schedule is today + 30
```
